### ISSUE TITLE
Script to setup Opendistro Elasticsearch default credentials and certs

### ISSUE THREAD

**Issue by arlake228** [perfsonar/archive#1]
When we install an RPM or Debian package we want to install a default set of self-signed SSL certificates and usernames/passwords.See https://github.com/perfsonar/archive/blob/main/scripts/pselastic_secure.sh for a rough version that was used in the archiving-sandbox to configure Elasticsearch. The setup for opendistro is slightly different so needs to be adapted for that. Specifically you want to do t This script will be run in the post-install section of the perfsonar-archive rpm. This means you can assume that Opendistro Elasticsearch, Opendistro Kibana and the perfSONAR logstash pipeline are all installed on the same host. Specifically it should do the following:

- Generat a server SSL certificate for Elasticsearch. Self-signed is fine. The current script uses and Elastic provided script which is not available in our case. You can just use openssl to do the same.

- Make elastic and Kibana listen on localhost. We will setup an HTTPD reverse proxy in the OS package. 

- Give anonymous users the "pscheduler_reader" role - a role that with read-only access to he pscheduler indices giving API access to unauthenticated users similar to what we have with Esmond today.

- Implement the same functionality as Elasticsearch's  elasticsearch-setup-passwords  script that creates an initial set of passwords for an initial administrator account with a random password. 

- Install users and roles such as this for Logstash. You probably don't need to change much here, the pselastic script should still work fine (in theory, will need to test)

- Update /etc/sysconfig/logstash with the Elastic search username and password. Again, if you get above working probably the code already in the script will just work,

**Comment by DanielNeto** [comment]
Done
