### ISSUE TITLE
SELinux setup not working for perfsonar-archive bundle on CentOS 7

### ISSUE THREAD

**Issue by arlake228** [perfsonar/archive#14]
On CentOS 7 if you do a "yum install perfsonar-archive" you will get a "Service Not Available" error if you try to go to https://HOST/opensearch. Disabling selinux with `setenforce 0` seems to make the issue go away. A toolkit install does not have this issue. The perfsonar-toolkit-web-services package does the SElinux setup for the toolkit. We could just add a dependency on this...though if I install it separately after installling  perfsonar-toolkit-web-services it does not seem to correct the issue. Possible this is an order of operations issue or something else toolkit is doing to make that work.

**Comment by mfeit-internet2** [comment]
FWIW, you may be able to find out what SELinux is on about by checking the logs and flipping the appropriate bit with `setsebool`.  pScheduler has a few things like thast.

I'm not a big fan of SELinux, but keeping it on may keep some security auditors happy.
