### ISSUE TITLE
perfsonar-archive RPM

### ISSUE THREAD

**Issue by arlake228** [perfsonar/archive#2]

**Comment by arlake228** [comment]
Create a working RPM of perfsonar-archive on CentOS 7. The goal is to create a package that will setup elastic, logstash and Kibana. Specifically it should have the following dependencies:

- opendistroforelasticsearch
- opendistroforelasticsearch-kibana
- perfsonar-logstash
- httpd

In the post install phase it will do the following:

- Run the script from issue #1 to setup credentials and certs
- Setup an httpd reverse proxy that forwards the following URLs:
   - /perfsonar/elastic -> localhost:9200
   - /perfsonar/logstash -> locahost:11283
   - perfsonar/kibana -> localhost:5601

**Comment by DanielNeto** [comment]
Packages created for version 5.0.0:
- perfsonar-archive
- perfsonar-dashboards
- perfsonar-logstash
- perfsonar-logstash-output-plugin
- perfsonar-elmond
