### ISSUE TITLE
documentation: confusing references to Esmond

### ISSUE THREAD

**Issue by igarny** [perfsonar/archive#22]
Hi Andy,

In the guidelines for the configuration of authentication
https://docs.perfsonar.net/multi_ma_install.html#scenario-2-writing-to-a-remote-archive-with-username-and-password-authentication 
the output provided as an example is confusing, since in its “_meta “ tag states Esmond

Similar to issue is with the example output for the IP based authentication.

Regards,
Ivan

**Comment by arlake228** [comment]
The examples there are 100% correct and MaDDash will not work without that line. That line tells MaDDash where to talk to Elmond. That can go away when MaDDash goes away in 5.1.0. The current instruction tell people to run a command and copy/paste the output. I think it would be more confusing to break down the output line-by-line.
