### ISSUE TITLE
Logstash config fails with IPv6 only host on Ubuntu systems

### ISSUE THREAD

**Issue by igarny** [perfsonar/archive#23]
Hi guys,

On Ubuntu the config for Logstash defaults to: 127.0.0.1 (not even localhost)
`# api.http.host: 127.0.0.1`

Even if one fixes this, the pScheduler pipeline also refers only to **localhost**, which in Ubuntu resolves to IPv4 Local interface

`input {
  http {
    host => "localhost"
    port => "11283" # ACII 112=p, 83=S
  }
`

**Comment by Rezi1999** [comment]
```
input {
  http {
    host => "::1"
    port => "11283" # ACII 112=p, 83=S
  }
}

after changing localhost to ::1, logstash listens only on ipv6 

`tcp6       0      0 ::1:11283               :::*                    LISTEN      717367/java`
```

**Comment by laeti-tia** [comment]
I believe this is solved with recent changes.  Reopen if not.
