### ISSUE TITLE
On Ubuntu 20: the script that generates the json output for inclusion into psconfig is NOT executable

### ISSUE THREAD

**Issue by igarny** [perfsonar/archive#24]
based on this doc: https://docs.perfsonar.net/multi_ma_install.html#scenario-2-writing-to-a-remote-archive-with-username-and-password-authentication
I would expect this script is executable:
`/usr/lib/perfsonar/archive/perfsonar-scripts/psconfig_archive.sh`

**Comment by laeti-tia** [comment]
Should be solved together with #37
